// Generated by https://quicktype.io

export interface JSON {
  technologies: Technology[];
  courses: Course[];
}

export interface Technology {
  _id?: string;
  name: string;
  description: string;
  difficulty: number;
  courses: Course[];
}

export interface Course {
  _id?: string;
  code: string;
  name: string;
  checked?: boolean
}
